openapi: 3.0.0
info:
  title: API de Livros
  version: 1.0.0
paths:
  /livros:
    get:
      summary: Retorna todos os livros
      responses:
        '200':
          description: Lista de livros
    post:
      summary: Adiciona um novo livro
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Livro'
      responses:
        '200':
          description: Livro adicionado com sucesso
  '/livros/{id}':
    get:
      summary: Retorna um livro pelo ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Livro encontrado
        '404':
          description: Livro não encontrado
    put:
      summary: Atualiza um livro pelo ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Livro'
      responses:
        '200':
          description: Livro atualizado com sucesso
        '404':
          description: Livro não encontrado
    delete:
      summary: Deleta um livro pelo ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Livro deletado com sucesso
        '404':
          description: Livro não encontrado
components:
  schemas:
    Livro:
      type: object
      properties:
        id:
          type: integer
        titulo:
          type: string
        autor:
          type: string
        anoPublicacao:
          type: integer
